ktor:
  deployment:
    port: "$BUFFERED_PORT:8080"
  application:
    modules:
      - com.angelma.SerializationKt.configureSerialization
      - com.angelma.StatusPagesKt.configureStatusPages
      - com.angelma.RoutingKt.configureRouting
      - com.angelma.CallLoggingKt.configureCallLogging
buffered:
  mediaDir: "$BUFFERED_MEDIA_DIR:../media"
