ktor:
  deployment:
    port: 8080
  application:
    modules:
      - com.angelma.SerializationKt.configureSerialization
      - com.angelma.StatusPagesKt.configureStatusPages
      - com.angelma.RoutingKt.configureRouting
